import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const alienAi = localFont({
  src: [
    {
      path: "../public/fonts/AlienAi-mLxP5.ttf",
      style: "normal",
    },
    {
      path: "../public/fonts/AlienAiItalic-PKnO7.ttf",
      style: "italic",
    },
  ],
  variable: "--font-alien",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alienAi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
